server:
  port: 8200

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webapp?serverTimezone=GMT&useSSL=false
    username: root
    password: Aa15013247811
    driver-class-name: com.mysql.cj.jdbc.Driver
jpa:
  hibernate:

    ddl-auto: update

  show-sql: true

